version: "3.7"

services:
  react-app:
    image: react-app
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - mern-app

  node-app:
    image: node-app
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - mern-app

  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - "27017:27017"
    networks:
      - mern-app

networks:
  mern-app:
    driver: bridge

volumes:
  mongo-data:
    driver: local
